services:
    - docker

addons:
    apt:
        packages:
            - python3-virtualenv
    homebrew:
        packages:
            - gmp
            - grpc
            - protobuf
            - boost
            - openssl
            - cmake
            - libtool
            - autoconf
            - automake
            - python
            # - llvm

matrix:
    include:
        - env: CI_TASK=contracts_check
          os: linux
          dist: bionic
          language: node_js
          node_js:
          - "10.16.3"
        - env: CI_TASK=pyclient_check CI_USE_DOCKER=1
          os: linux
          language: minimal
        - env: CI_TASK=build CI_CONFIG=Release CI_USE_DOCKER=1
          os: linux
          language: minimal
        - env: CI_TASK=build CI_CONFIG=Debug CI_USE_DOCKER=1 CI_CHECK_FORMAT=1
          os: linux
          language: minimal
        - env: CI_TASK=build CI_CONFIG=Release
          os: osx
          osx_image: xcode11
        - env: CI_TASK=build CI_CONFIG=Debug
          os: osx
          osx_image: xcode11
        - env: CI_TASK=build CI_CONFIG=Release CI_ZKSNARK=PGHR13 CI_USE_DOCKER=1
          os: linux
          language: minimal

script: CI_USE_DOCKER=${CI_USE_DOCKER} CI_CONFIG=${CI_CONFIG} CI_ZKSNARK=${CI_ZKSNARK} travis_wait 30 scripts/ci ${CI_TASK}
